function [Dates, Data, Assets, Map] = importfile(workbookFile, sheetName)
%IMPORTFILE Import numeric data from a spreadsheet
%   DATA = IMPORTFILE(FILE) reads all numeric data from the first worksheet
%   in the Microsoft Excel spreadsheet file named FILE and returns the
%   numeric data.
%
%   DATA = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   headers = importfile('stock_data.xls','Sheet1');
%
%   See also XLSREAD.

% Auto-generated by MATLAB 

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

%% numeric data matrix with NaN
[~, ~, raw] = xlsread(workbookFile,sheetName,'B2:AT309');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x),raw); % Find non-numeric cells
Data = raw;
Data(R) = {NaN}; % Replace non-numeric cells

% Create output variable
Data = cell2mat(Data);

%% headers
[~, ~, Assets] = xlsread(workbookFile,sheetName,'B1:AT1');
Assets(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),Assets)) = {''};

%% dates
[~, ~, raw, dateNums] = xlsread(workbookFile,sheetName,'A2:A309','',@convertSpreadsheetDates);

%% Replace date strings by MATLAB datenums
R = ~cellfun(@isequalwithequalnans,dateNums,raw) & cellfun('isclass',raw,'char'); % Find Excel dates
raw(R) = dateNums(R);

%% Create output variable
Dates = cell2mat(raw);

Map = xlsread(workbookFile,'Sheet2');
